DOMAIN = "btr5"

DEFAULT_TIMEOUT = 10.0
DEFAULT_STEP_SIZE = 1
MIN_STEP_SIZE = 1
MAX_STEP_SIZE = 60
DEFAULT_DEBOUNCE_SECONDS = 0.5
MIN_DEBOUNCE_SECONDS = 0.1
MAX_DEBOUNCE_SECONDS = 5.0
BATTERY_POLL_INTERVAL_MINUTES = 10
MAX_BATTERY_PERCENT = 100
PERSISTENT_RECONNECT_ATTEMPTS = 10
PERSISTENT_RECONNECT_DELAY_SECONDS = 3.0

GAIA_VENDOR_CSR = 0x000A
GAIA_ACK_MASK = 0x8000
CMD_AV_REMOTE_CONTROL = 0x021F
CMD_BATTERY = 0x0414
PAYLOAD_VOLUME_UP = 0x41
PAYLOAD_VOLUME_DOWN = 0x42
